version: '3.8'

services:
  app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_PORT=3000
      - HOST=0.0.0.0
    command: sh -c "npm install && npm run dev"
